name: Update site

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: CD/scripts
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Test passed, deploying updated version website'
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

      - name: run deploy script
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} "bash -s" < ./deploy_site.sh

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Pytest failed, check pytest results and try again'
